extends: .github
shared:
  check_runs: &CheckRuns
    - check-success=test (ubuntu-24.04)
    - check-success=test (windows-2025)
    - check-success=test (macos-15)

queue_rules:
  - name: dependencies
    autoqueue: true
    queue_conditions:
      - base=main
      - label!=manual merge
      - or:
          - author = renovate[bot]
          - author = dependabot[bot]
    merge_method: merge
    batch_size: 7
    batch_max_wait_time: 5min
    commit_message_template:
    queue_branch_merge_method: fast-forward

  - name: default
    autoqueue: true
    queue_conditions:
      - base=main
      - label!=manual merge
    commit_message_template: |
      {{ title }} (#{{ number }})

      {{ body }}
    merge_method: squash

pull_request_rules:
  - name: request review
    conditions:
      - -author=dependabot[bot]
      - -author=renovate[bot]
      - -author=mergify-ci-bot
      - -merged
      - -closed
      - and: *CheckRuns
      - "#approved-reviews-by=0"
      - "#changes-requested-reviews-by=0"
      - "review-requested!=@devs"
    actions:
      request_reviews:
        teams:
          - devs


merge_protections:
  - name: 🤖 Continuous Integration
    if: []
    success_conditions:
      - and: *CheckRuns

  - name: 👀 Review Requirements
    if: []
    success_conditions:
      - or:
        - "#approved-reviews-by>=2"
        - author = dependabot[bot]
        - author = renovate[bot]
        - author = mergify-ci-bot


merge_queue:
  max_parallel_checks: 5

merge_protections_settings:
  reporting_method: deployments
