//! Stack-context resolution helpers.
//!
//! Shared by the GitHub-API-backed stack subcommands (`checkout`,
//! `sync`, `list`, `open`, `push`) — port of the per-command
//! preamble that Python's `mergify_cli/stack/cli.py` runs inside
//! the click group:
//!
//! - `github_server` from the `mergify-cli.github-server` git
//!   config key, falling back to `https://api.github.com/`.
//! - Repository `(owner, repo)` from either an explicit
//!   `--repository OWNER/REPO` argument or
//!   `git config remote.<remote>.url` parsed by [`parse_slug`].
//! - Default branch prefix from
//!   `mergify-cli.stack-branch-prefix`, falling back to
//!   `stack/<author>`.
//! - URL slug parser handling both HTTPS (`https://github.com/o/r`)
//!   and SSH (`git@github.com:o/r.git`) shapes.

use std::path::Path;

use crate::git::run_git_capture;
use std::sync::LazyLock;

use mergify_core::CliError;
use regex::Regex;
use url::Url;

/// `--<8 hex>` suffix that `stack push` appends to auto-generated
/// branch names. Mirrors `_SLUG_SUFFIX_RE` in
/// `mergify_cli/stack/push.py`.
static SLUG_SUFFIX_RE: LazyLock<Regex> = LazyLock::new(|| Regex::new(r"--[0-9a-f]{8}$").unwrap());

/// Legacy `/I<40 hex>` Change-Id suffix on stack branches.
static CHANGEID_BRANCH_SUFFIX_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"/I[0-9a-z]{40}$").unwrap());

/// Reject local branches that look auto-generated by
/// `mergify stack push` — running stack-modifying commands on a
/// generated leaf-branch instead of the parent stack branch is a
/// data-loss footgun. Mirrors
/// `mergify_cli/stack/push.py::check_local_branch`.
pub fn check_local_branch(branch_name: &str, branch_prefix: &str) -> Result<(), CliError> {
    if !branch_name.starts_with(branch_prefix) {
        return Ok(());
    }
    if CHANGEID_BRANCH_SUFFIX_RE.is_match(branch_name) || SLUG_SUFFIX_RE.is_match(branch_name) {
        return Err(CliError::InvalidState(format!(
            "Local branch `{branch_name}` is a branch generated by Mergify CLI. \
             Switch to the parent stack branch before running this command."
        )));
    }
    Ok(())
}

/// Build the "your local branch targets itself" error every stack
/// command that resolves a trunk raises when the checked-out branch
/// *is* the trunk it would land on.
///
/// Mirrors `sync.py` / `list.py`: a first line carrying the resolved
/// remote URL (`git remote get-url <remote>`, omitted gracefully
/// when that fails) followed by the two copy-pasteable git commands.
/// Returns [`CliError::InvalidState`] (exit 7), matching Python.
#[must_use]
pub fn targets_itself_error(
    repo_dir: Option<&Path>,
    dest_branch: &str,
    remote: &str,
    base_branch: &str,
) -> CliError {
    let location = run_git_capture(repo_dir, &["remote", "get-url", remote])
        .ok()
        .filter(|url| !url.is_empty())
        .map(|url| format!(" (at {url}@{base_branch})"))
        .unwrap_or_default();
    CliError::InvalidState(format!(
        "your local branch `{dest_branch}` targets itself: \
         `{remote}/{base_branch}`{location}\n\
         * To fix the target branch: \
         `git branch {dest_branch} --set-upstream-to={remote}/{base_branch}`\n\
         * To rename your local branch: \
         `git branch -M {dest_branch} new-branch-name`"
    ))
}

/// Owner + repository name pair, e.g. `("Mergifyio", "mergify-cli")`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RepoSlug {
    pub owner: String,
    pub repo: String,
}

/// Parse a remote URL into `(owner, repo)`. Handles both HTTPS
/// (`https://github.com/owner/repo.git`) and SSH
/// (`git@github.com:owner/repo.git`) shapes. The trailing `.git`
/// suffix is stripped; a trailing `/` on the path is tolerated.
///
/// Mirrors `mergify_cli/utils.py::get_slug`.
pub fn parse_slug(url: &str) -> Result<RepoSlug, CliError> {
    // SSH shape: `user@host:owner/repo[.git]` — no `//` and the
    // path lives after the first `:`. Python's `urlparse` returns
    // empty netloc for this shape; we mirror by checking for `://`.
    let path = if url.contains("://") {
        // Validate via the `url` crate so we surface a clear error
        // on garbage input.
        let parsed = Url::parse(url).map_err(|e| {
            CliError::InvalidState(format!("could not parse remote URL '{url}': {e}"))
        })?;
        parsed
            .path()
            .trim_start_matches('/')
            .trim_end_matches('/')
            .to_string()
    } else {
        let (_user_host, path) = url.split_once(':').ok_or_else(|| {
            CliError::InvalidState(format!(
                "remote URL '{url}' is not parseable as HTTPS or SSH"
            ))
        })?;
        path.trim_end_matches('/').to_string()
    };
    let (owner, repo) = path.split_once('/').ok_or_else(|| {
        CliError::InvalidState(format!("remote URL '{url}' has no `<owner>/<repo>` path"))
    })?;
    let repo = repo.strip_suffix(".git").unwrap_or(repo);
    if owner.is_empty() || repo.is_empty() {
        return Err(CliError::InvalidState(format!(
            "remote URL '{url}' parses to an empty owner or repo"
        )));
    }
    Ok(RepoSlug {
        owner: owner.to_string(),
        repo: repo.to_string(),
    })
}

/// Resolve the repository from an explicit `--repository OWNER/REPO`
/// flag (preferred) or, when missing, by reading
/// `remote.<remote>.url` from git config and slug-parsing it.
pub fn resolve_repo(
    repo_dir: Option<&Path>,
    explicit_repository: Option<&str>,
    remote: &str,
) -> Result<RepoSlug, CliError> {
    if let Some(value) = explicit_repository {
        let (owner, repo) = value.split_once('/').ok_or_else(|| {
            CliError::InvalidState("--repository must be in the format 'owner/repo'".to_string())
        })?;
        if owner.is_empty() || repo.is_empty() {
            return Err(CliError::InvalidState(
                "--repository must be in the format 'owner/repo'".to_string(),
            ));
        }
        return Ok(RepoSlug {
            owner: owner.to_string(),
            repo: repo.to_string(),
        });
    }
    let key = format!("remote.{remote}.url");
    let url = run_git_capture(repo_dir, &["config", "--get", &key])?;
    parse_slug(&url)
}

/// Resolve `mergify-cli.github-server` from git config, falling
/// back to `https://api.github.com/`. The Python implementation
/// rewrites the scheme to `https` and tacks on `/api/v3` when the
/// host is not `api.github.com` (so GitHub Enterprise users can
/// configure just the host).
///
/// The `MERGIFY_GITHUB_SERVER` env var overrides everything and
/// is taken verbatim — production users go through git config so
/// the https coercion still applies to them, but tests and ad-
/// hoc CI setups can point at any URL (including plain `http://`
/// for local wiremock servers) without the coercion getting in
/// the way.
pub fn resolve_github_server(repo_dir: Option<&Path>) -> Result<Url, CliError> {
    if let Ok(raw) = std::env::var("MERGIFY_GITHUB_SERVER")
        && !raw.is_empty()
    {
        return Url::parse(&raw).map_err(|e| {
            CliError::InvalidState(format!("invalid MERGIFY_GITHUB_SERVER '{raw}': {e}"))
        });
    }
    let configured = run_git_capture(repo_dir, &["config", "--get", "mergify-cli.github-server"])
        .unwrap_or_default();
    let raw = if configured.is_empty() {
        "https://api.github.com/".to_string()
    } else {
        configured
    };
    let mut url = Url::parse(&raw).map_err(|e| {
        CliError::InvalidState(format!("invalid mergify-cli.github-server '{raw}': {e}"))
    })?;
    // Force scheme to https — Python's `_replace(scheme="https")`.
    if url.scheme() != "https" {
        url.set_scheme("https")
            .map_err(|()| CliError::InvalidState(format!("could not coerce '{raw}' to https")))?;
    }
    let host = url.host_str().unwrap_or("").to_string();
    if host == "api.github.com" {
        url.set_path("");
    } else {
        url.set_path("/api/v3");
    }
    Ok(url)
}

/// Resolve the default branch prefix from
/// `mergify-cli.stack-branch-prefix`, falling back to
/// `stack/<author>`. Mirrors `utils.get_default_branch_prefix`.
#[must_use]
pub fn resolve_default_branch_prefix(repo_dir: Option<&Path>, author: &str) -> String {
    let configured = run_git_capture(
        repo_dir,
        &["config", "--get", "mergify-cli.stack-branch-prefix"],
    )
    .unwrap_or_default();
    if configured.is_empty() {
        format!("stack/{author}")
    } else {
        configured
    }
}

/// `mergify-cli.stack-create-as-draft`, defaulting to `false`.
/// Mirrors `utils.get_default_create_as_draft` — only treats the
/// literal string `"true"` as true so a value like `1` won't
/// silently flip the default.
#[must_use]
pub fn resolve_default_create_as_draft(repo_dir: Option<&Path>) -> bool {
    run_git_capture(
        repo_dir,
        &["config", "--get", "mergify-cli.stack-create-as-draft"],
    )
    .is_ok_and(|v| v == "true")
}

/// `mergify-cli.stack-keep-pr-title-body`, defaulting to `false`.
/// Mirrors `utils.get_default_keep_pr_title_body`.
#[must_use]
pub fn resolve_default_keep_pr_title_body(repo_dir: Option<&Path>) -> bool {
    run_git_capture(
        repo_dir,
        &["config", "--get", "mergify-cli.stack-keep-pr-title-body"],
    )
    .is_ok_and(|v| v == "true")
}

/// `mergify-cli.stack-revision-history`, defaulting to `true`.
/// Mirrors `utils.get_default_revision_history` — opt-out: only
/// the literal string `"false"` disables the feature.
#[must_use]
pub fn resolve_default_revision_history(repo_dir: Option<&Path>) -> bool {
    run_git_capture(
        repo_dir,
        &["config", "--get", "mergify-cli.stack-revision-history"],
    )
    .map_or(true, |v| v != "false")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_https_url() {
        let slug = parse_slug("https://github.com/owner/repo.git").unwrap();
        assert_eq!(slug.owner, "owner");
        assert_eq!(slug.repo, "repo");
    }

    #[test]
    fn targets_itself_includes_remote_url_and_both_git_commands() {
        let dir = tempfile::tempdir().unwrap();
        for args in [
            &["init", "-q", "-b", "main"][..],
            &[
                "remote",
                "add",
                "origin",
                "https://github.com/owner/repo.git",
            ],
        ] {
            let ok = crate::test_env::isolated_git()
                .arg("-C")
                .arg(dir.path())
                .args(args)
                .status()
                .unwrap()
                .success();
            assert!(ok, "git {args:?} failed");
        }
        let err = targets_itself_error(Some(dir.path()), "main", "origin", "main");
        match err {
            CliError::InvalidState(msg) => {
                assert!(
                    msg.contains(
                        "your local branch `main` targets itself: `origin/main` \
                         (at https://github.com/owner/repo.git@main)"
                    ),
                    "got: {msg}"
                );
                assert!(
                    msg.contains(
                        "* To fix the target branch: \
                         `git branch main --set-upstream-to=origin/main`"
                    ),
                    "got: {msg}"
                );
                assert!(
                    msg.contains(
                        "* To rename your local branch: \
                         `git branch -M main new-branch-name`"
                    ),
                    "got: {msg}"
                );
            }
            other => panic!("expected InvalidState, got: {other:?}"),
        }
    }

    #[test]
    fn targets_itself_omits_location_when_remote_url_unresolvable() {
        let dir = tempfile::tempdir().unwrap();
        let ok = crate::test_env::isolated_git()
            .arg("-C")
            .arg(dir.path())
            .args(["init", "-q", "-b", "main"])
            .status()
            .unwrap()
            .success();
        assert!(ok);
        // No remote configured → `git remote get-url` fails; the
        // `(at ...)` parenthetical is dropped without erroring.
        let err = targets_itself_error(Some(dir.path()), "main", "origin", "main");
        match err {
            CliError::InvalidState(msg) => {
                assert!(
                    msg.contains("targets itself: `origin/main`\n"),
                    "location parenthetical should be absent: {msg}"
                );
                assert!(!msg.contains("(at "), "got: {msg}");
                assert!(msg.contains("--set-upstream-to=origin/main"), "got: {msg}");
            }
            other => panic!("expected InvalidState, got: {other:?}"),
        }
    }

    #[test]
    fn parses_https_url_without_git_suffix() {
        let slug = parse_slug("https://github.com/owner/repo").unwrap();
        assert_eq!(slug.repo, "repo");
    }

    #[test]
    fn parses_https_url_with_trailing_slash() {
        let slug = parse_slug("https://github.com/owner/repo/").unwrap();
        assert_eq!(slug.repo, "repo");
    }

    #[test]
    fn parses_ssh_url() {
        let slug = parse_slug("git@github.com:owner/repo.git").unwrap();
        assert_eq!(slug.owner, "owner");
        assert_eq!(slug.repo, "repo");
    }

    #[test]
    fn parses_ssh_url_without_git_suffix() {
        let slug = parse_slug("git@github.com:owner/repo").unwrap();
        assert_eq!(slug.repo, "repo");
    }

    #[test]
    fn invalid_url_errors() {
        let err = parse_slug("not-a-url").unwrap_err();
        match err {
            CliError::InvalidState(msg) => {
                assert!(
                    msg.contains("not parseable") || msg.contains("invalid"),
                    "got: {msg}"
                );
            }
            other => panic!("unexpected: {other:?}"),
        }
    }

    #[test]
    fn empty_components_error() {
        let err = parse_slug("https://github.com//repo").unwrap_err();
        match err {
            CliError::InvalidState(_) => {}
            other => panic!("unexpected: {other:?}"),
        }
    }

    #[test]
    fn check_local_branch_accepts_non_generated_names() {
        check_local_branch("feature", "stack/me").unwrap();
        check_local_branch("stack/me", "stack/me").unwrap();
    }

    #[test]
    fn check_local_branch_rejects_slug_suffix() {
        let err = check_local_branch("stack/me/feature/feat-x--abcd1234", "stack/me").unwrap_err();
        match err {
            CliError::InvalidState(msg) => assert!(msg.contains("generated"), "got: {msg}"),
            other => panic!("unexpected: {other:?}"),
        }
    }

    #[test]
    fn check_local_branch_rejects_changeid_suffix() {
        let err = check_local_branch(
            "stack/me/feature/Iaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
            "stack/me",
        )
        .unwrap_err();
        match err {
            CliError::InvalidState(_) => {}
            other => panic!("unexpected: {other:?}"),
        }
    }
}
