//! `mergify stack sync [--dry-run]` — rebase the current stack
//! onto the trunk, dropping commits whose PR has already been
//! merged.
//!
//! Port of `mergify_cli/stack/sync.py::stack_sync`. The flow:
//!
//! 1. Validate the local branch isn't auto-generated by
//!    `stack push` (see [`crate::stack_context::check_local_branch`]).
//! 2. Resolve the GitHub repository, the merge-base with the
//!    trunk (`git merge-base --fork-point`), and the stack's
//!    remote PRs.
//! 3. Bucket local commits via
//!    [`crate::sync_status::classify`] — merged vs. remaining.
//! 4. `--dry-run` short-circuits with a plan. Otherwise fetch
//!    the trunk and either:
//!    - `git pull --rebase` when nothing is merged, or
//!    - `git rebase -i` with `GIT_SEQUENCE_EDITOR` pointing at
//!      this binary's `_internal rebase-todo-rewrite --action
//!      drop --shas <merged>` to drop the merged commits in a
//!      single rebase pass.

use std::path::Path;

use mergify_core::CliError;
use mergify_core::HttpClient;

use crate::git::{
    resolve_repo_toplevel, run_git_capture, run_git_silent, shell_quote, spawn_rebase,
};
use crate::local_commits;
use crate::remote_changes;
use crate::stack_context;
use crate::sync_status::{self, SyncStatus};
use crate::trunk;

#[derive(Debug, Clone)]
pub enum Outcome {
    /// Plan was rendered (dry-run path).
    DryRun(SyncStatus),
    /// Real sync ran to completion. `dropped_count` is what we
    /// rebased away.
    Synced {
        status: SyncStatus,
        dropped_count: usize,
    },
}

pub struct Options<'a> {
    pub repo_dir: Option<&'a Path>,
    pub client: &'a HttpClient,
    pub user: &'a str,
    pub repo: &'a str,
    pub author: &'a str,
    pub branch_prefix: &'a str,
    /// `(remote, branch)` of the trunk. Required.
    pub trunk: (&'a str, &'a str),
    pub dry_run: bool,
    pub mergify_binary: &'a Path,
}

pub async fn run(opts: &Options<'_>) -> Result<Outcome, CliError> {
    let repo_dir = resolve_repo_toplevel(opts.repo_dir)?;
    let dest_branch = trunk::git_get_branch_name(Some(&repo_dir))?;

    stack_context::check_local_branch(&dest_branch, opts.branch_prefix)?;

    let (remote, base_branch) = opts.trunk;
    if base_branch == dest_branch {
        return Err(stack_context::targets_itself_error(
            Some(&repo_dir),
            &dest_branch,
            remote,
            base_branch,
        ));
    }

    let stack_prefix = if opts.branch_prefix.is_empty() {
        dest_branch.clone()
    } else {
        format!("{prefix}/{dest_branch}", prefix = opts.branch_prefix)
    };

    let trunk_ref = format!("{remote}/{base_branch}");
    let base_commit_sha =
        match run_git_capture(Some(&repo_dir), &["merge-base", "--fork-point", &trunk_ref]) {
            Ok(sha) if !sha.is_empty() => sha,
            // `--fork-point` falls back to the plain merge-base when
            // there's no reflog history (CI sandboxes, freshly cloned
            // repos). Match Python's "any non-empty result is fine"
            // tolerance.
            _ => run_git_capture(Some(&repo_dir), &["merge-base", &trunk_ref, "HEAD"])?,
        };
    if base_commit_sha.is_empty() {
        return Err(CliError::StackNotFound(format!(
            "common commit between `{trunk_ref}` and `{dest_branch}` branches not found"
        )));
    }

    let remote_changes = remote_changes::get_remote_changes(
        opts.client,
        opts.user,
        opts.repo,
        &stack_prefix,
        opts.author,
    )
    .await?;

    let local = local_commits::read(&repo_dir, &base_commit_sha, "HEAD")?;
    let status = sync_status::classify(
        dest_branch.clone(),
        trunk_ref.clone(),
        &local,
        remote_changes,
    )?;

    if opts.dry_run {
        return Ok(Outcome::DryRun(status));
    }

    // Real sync.
    run_git_silent(Some(&repo_dir), &["fetch", remote, base_branch])?;
    let dropped_count = status.merged.len();
    if status.up_to_date() || status.all_merged() {
        // Either nothing to drop, or every commit got merged.
        // Both cases collapse to a plain pull --rebase.
        run_git_silent(Some(&repo_dir), &["pull", "--rebase", remote, base_branch])?;
    } else {
        // Mixed case: drop merged commits in a single
        // `git rebase -i`, dispatched through the existing
        // rebase-todo `Action::Drop` machinery.
        let merged_shas: Vec<String> = status.merged.iter().map(|m| m.commit_sha.clone()).collect();
        let editor = build_drop_editor(opts.mergify_binary, &merged_shas);
        let trunk_ref_owned = trunk_ref.clone();
        spawn_rebase(&repo_dir, &trunk_ref_owned, Some(&editor))?;
    }
    Ok(Outcome::Synced {
        status,
        dropped_count,
    })
}

fn build_drop_editor(binary: &Path, merged_shas: &[String]) -> String {
    let bin = shell_quote(&binary.to_string_lossy());
    let shas = shell_quote(&merged_shas.join(","));
    format!("{bin} _internal rebase-todo-rewrite --action drop --shas {shas}")
}
