//! `mergify stack sync [--dry-run]` — rebase the current stack
//! onto the trunk, dropping commits whose PR has already been
//! merged.
//!
//! Port of `mergify_cli/stack/sync.py::stack_sync`. The flow:
//!
//! 1. Validate the local branch isn't auto-generated by
//!    `stack push` (see [`crate::stack_context::check_local_branch`]).
//! 2. Resolve the GitHub repository, the merge-base with the
//!    trunk (`git merge-base --fork-point`), and the stack's
//!    remote PRs.
//! 3. Bucket local commits via
//!    [`crate::sync_status::classify`] — merged vs. remaining.
//! 4. `--dry-run` short-circuits with a plan. Otherwise fetch
//!    the trunk and either:
//!    - `git pull --rebase` when nothing is merged, or
//!    - `git rebase -i` with `GIT_SEQUENCE_EDITOR` pointing at
//!      this binary's `_internal rebase-todo-rewrite --action
//!      drop --shas <merged>` to drop the merged commits in a
//!      single rebase pass.

use std::path::Path;

use mergify_core::CliError;
use mergify_core::HttpClient;

use crate::git::{
    compute_base_commit_sha, resolve_repo_toplevel, run_git_silent, shell_quote, spawn_rebase,
    spawn_rebase_captured,
};
use crate::local_commits;
use crate::remote_changes;
use crate::stack_context;
use crate::sync_status::{self, SyncStatus};
use crate::trunk;

#[derive(Debug, Clone)]
pub enum Outcome {
    /// Plan was rendered (dry-run path).
    DryRun(SyncStatus),
    /// Real sync ran to completion. `dropped_count` is what we
    /// rebased away.
    Synced {
        status: SyncStatus,
        dropped_count: usize,
    },
}

pub struct Options<'a> {
    pub repo_dir: Option<&'a Path>,
    pub client: &'a HttpClient,
    pub user: &'a str,
    pub repo: &'a str,
    pub author: &'a str,
    pub branch_prefix: &'a str,
    /// `(remote, branch)` of the trunk. Required.
    pub trunk: (&'a str, &'a str),
    pub dry_run: bool,
    pub mergify_binary: &'a Path,
    /// Capture the rebase's git output instead of letting it reach
    /// the terminal — set by `stack push`, which drives the rebase
    /// under a progress spinner that owns the terminal.
    pub quiet: bool,
    /// Remote changes already fetched by the caller (the `stack push`
    /// pre-flight). When `Some`, `run` reuses them instead of
    /// re-running the search + per-PR GETs that `get_remote_changes`
    /// does. `None` for the standalone `stack sync` command.
    pub prefetched_remote_changes: Option<Vec<remote_changes::RemoteChange>>,
    /// Skip the `git fetch <remote> <base>` pre-rebase. Set by
    /// `stack push`, whose pre-flight already fetched the trunk.
    pub skip_trunk_fetch: bool,
}

pub async fn run(opts: &Options<'_>) -> Result<Outcome, CliError> {
    let repo_dir = resolve_repo_toplevel(opts.repo_dir)?;
    let dest_branch = trunk::git_get_branch_name(Some(&repo_dir))?;

    stack_context::check_local_branch(&dest_branch, opts.branch_prefix)?;

    let (remote, base_branch) = opts.trunk;
    if base_branch == dest_branch {
        return Err(stack_context::targets_itself_error(
            Some(&repo_dir),
            &dest_branch,
            remote,
            base_branch,
        ));
    }

    let stack_prefix = if opts.branch_prefix.is_empty() {
        dest_branch.clone()
    } else {
        format!("{prefix}/{dest_branch}", prefix = opts.branch_prefix)
    };

    let trunk_ref = format!("{remote}/{base_branch}");
    let base_commit_sha = compute_base_commit_sha(&repo_dir, &trunk_ref, &dest_branch)?;

    let remote_changes = match &opts.prefetched_remote_changes {
        Some(changes) => changes.clone(),
        None => {
            remote_changes::get_remote_changes(
                opts.client,
                opts.user,
                opts.repo,
                &stack_prefix,
                opts.author,
            )
            .await?
        }
    };

    let local = local_commits::read(&repo_dir, &base_commit_sha, "HEAD")?;
    let status = sync_status::classify(
        dest_branch.clone(),
        trunk_ref.clone(),
        &local,
        remote_changes,
    )?;

    if opts.dry_run {
        return Ok(Outcome::DryRun(status));
    }

    // Real sync.
    if !opts.skip_trunk_fetch {
        run_git_silent(Some(&repo_dir), &["fetch", remote, base_branch])?;
    }
    let dropped_count = status.merged.len();
    if status.up_to_date() || status.all_merged() {
        // Either nothing to drop, or every commit got merged.
        // Both cases collapse to a plain pull --rebase.
        run_git_silent(Some(&repo_dir), &["pull", "--rebase", remote, base_branch]).map_err(
            // A failed `pull --rebase` is almost always a conflict;
            // give the same recovery guidance and Conflict exit code as
            // `spawn_rebase` rather than a bare stderr. (`run_git_silent`
            // only ever returns `Generic`, so map unconditionally.)
            |_| {
                CliError::Conflict(
                    "rebase failed — there may be conflicts\n\
                     Resolve conflicts then run: git rebase --continue\n\
                     Or abort the rebase with: git rebase --abort"
                        .to_string(),
                )
            },
        )?;
    } else {
        // Mixed case: drop merged commits in a single
        // `git rebase -i`, dispatched through the existing
        // rebase-todo `Action::Drop` machinery.
        let merged_shas: Vec<String> = status.merged.iter().map(|m| m.commit_sha.clone()).collect();
        let editor = build_drop_editor(opts.mergify_binary, &merged_shas);
        let trunk_ref_owned = trunk_ref.clone();
        // Trunk already carries the squash-merged equivalents of the
        // commits we're dropping, so they must stay in the todo for
        // the drop editor to find them — see `spawn_rebase`.
        if opts.quiet {
            spawn_rebase_captured(&repo_dir, &trunk_ref_owned, Some(&editor), true)?;
        } else {
            spawn_rebase(&repo_dir, &trunk_ref_owned, Some(&editor), true)?;
        }
    }
    Ok(Outcome::Synced {
        status,
        dropped_count,
    })
}

fn build_drop_editor(binary: &Path, merged_shas: &[String]) -> String {
    let bin = shell_quote(&binary.to_string_lossy());
    let shas = shell_quote(&merged_shas.join(","));
    format!("{bin} _internal rebase-todo-rewrite --action drop --shas {shas}")
}
