#
#  Copyright © 2021-2026 Mergify SAS
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
from __future__ import annotations

import datetime
import json
from typing import TYPE_CHECKING
from unittest import mock

import pytest

from mergify_cli import utils
from mergify_cli.exit_codes import ExitCode
from mergify_cli.stack import changes
from mergify_cli.stack import push
from mergify_cli.tests import utils as test_utils


if TYPE_CHECKING:
    import respx

    from mergify_cli import github_types


@pytest.mark.parametrize(
    "valid_branch_name",
    [
        ("my-branch"),
        ("prefix/my-branch"),
        ("my-branch/I29617d37762fd69809c255d7e7073cb11f8fbf50"),
    ],
)
def test_check_local_branch_valid(valid_branch_name: str) -> None:
    # Should not raise an error
    push.check_local_branch(
        branch_name=valid_branch_name,
        branch_prefix="prefix",
    )


def test_check_local_branch_invalid() -> None:
    with pytest.raises(
        push.LocalBranchInvalidError,
        match="Local branch is a branch generated by Mergify CLI",
    ):
        push.check_local_branch(
            branch_name="prefix/my-branch/I29617d37762fd69809c255d7e7073cb11f8fbf50",
            branch_prefix="prefix",
        )


@pytest.mark.respx(base_url="https://api.github.com/")
async def test_stack_push_forwards_no_verify(
    git_mock: test_utils.GitMock,
    respx_mock: respx.MockRouter,
) -> None:
    git_mock.commit(
        test_utils.Commit(
            sha="commit1_sha",
            title="Title commit 1",
            message="Message commit 1",
            change_id="I29617d37762fd69809c255d7e7073cb11f8fbf50",
        ),
    )
    git_mock.finalize(no_verify=True)

    respx_mock.get("/user").respond(200, json={"login": "author"})
    respx_mock.get("/search/issues").respond(200, json={"items": []})
    respx_mock.post("/repos/user/repo/pulls").respond(
        200,
        json={
            "html_url": "https://github.com/repo/user/pull/1",
            "number": "1",
            "title": "Title commit 1",
            "head": {"sha": "commit1_sha"},
            "state": "open",
            "merged_at": None,
            "draft": False,
            "node_id": "",
        },
    )
    respx_mock.get("/repos/user/repo/issues/1/comments").respond(200, json=[])

    await push.stack_push(
        github_server="https://api.github.com/",
        token="",
        skip_rebase=False,
        next_only=False,
        branch_prefix="",
        dry_run=False,
        trunk=("origin", "main"),
        no_verify=True,
    )

    assert git_mock.has_been_called_with(
        "push",
        "--atomic",
        "--no-verify",
        "--force-with-lease=refs/heads/current-branch/title-commit-1--29617d37:",
        "origin",
        "commit1_sha:refs/heads/current-branch/title-commit-1--29617d37",
    )


async def test_push_branches_no_verify(git_mock: test_utils.GitMock) -> None:
    local_changes = [
        changes.LocalChange(
            id=changes.ChangeId("I29617d37762fd69809c255d7e7073cb11f8fbf50"),
            pull=None,
            commit_sha="commit1_sha",
            title="Title",
            message="Message",
            base_branch="main",
            dest_branch="stack/title--29617d37",
            action="create",
        ),
    ]
    git_mock.mock(
        "push",
        "--atomic",
        "--no-verify",
        "--force-with-lease=refs/heads/stack/title--29617d37:",
        "origin",
        "commit1_sha:refs/heads/stack/title--29617d37",
        output="",
    )

    await push.push_branches("origin", local_changes, no_verify=True)

    assert git_mock.has_been_called_with(
        "push",
        "--atomic",
        "--no-verify",
        "--force-with-lease=refs/heads/stack/title--29617d37:",
        "origin",
        "commit1_sha:refs/heads/stack/title--29617d37",
    )


@pytest.mark.respx(base_url="https://api.github.com/")
async def test_stack_create(
    git_mock: test_utils.GitMock,
    respx_mock: respx.MockRouter,
) -> None:
    # Mock 2 commits on branch `current-branch`
    git_mock.commit(
        test_utils.Commit(
            sha="commit1_sha",
            title="Title commit 1",
            message="Message commit 1",
            change_id="I29617d37762fd69809c255d7e7073cb11f8fbf50",
        ),
    )
    git_mock.commit(
        test_utils.Commit(
            sha="commit2_sha",
            title="Title commit 2",
            message="Message commit 2",
            change_id="I29617d37762fd69809c255d7e7073cb11f8fbf51",
        ),
    )
    git_mock.finalize()

    # Mock HTTP calls
    respx_mock.get("/user").respond(200, json={"login": "author"})
    respx_mock.get("/search/issues").respond(200, json={"items": []})
    post_pull1_mock = respx_mock.post(
        "/repos/user/repo/pulls",
        json__title="Title commit 1",
    ).respond(
        200,
        json={
            "html_url": "https://github.com/repo/user/pull/1",
            "number": "1",
            "title": "Title commit 1",
            "head": {"sha": "commit1_sha"},
            "state": "open",
            "merged_at": None,
            "draft": False,
            "node_id": "",
        },
    )
    post_pull2_mock = respx_mock.post(
        "/repos/user/repo/pulls",
        json__title="Title commit 2",
    ).respond(
        200,
        json={
            "html_url": "https://github.com/repo/user/pull/2",
            "number": "2",
            "title": "Title commit 2",
            "head": {"sha": "commit2_sha"},
            "state": "open",
            "merged_at": None,
            "draft": False,
            "node_id": "",
        },
    )
    respx_mock.get("/repos/user/repo/issues/1/comments").respond(200, json=[])
    post_comment1_mock = respx_mock.post("/repos/user/repo/issues/1/comments").respond(
        200,
    )
    respx_mock.get("/repos/user/repo/issues/2/comments").respond(200, json=[])
    post_comment2_mock = respx_mock.post("/repos/user/repo/issues/2/comments").respond(
        200,
    )

    await push.stack_push(
        github_server="https://api.github.com/",
        token="",
        skip_rebase=False,
        next_only=False,
        branch_prefix="",
        dry_run=False,
        trunk=("origin", "main"),
    )

    # First pull request is created
    assert len(post_pull1_mock.calls) == 1
    assert json.loads(post_pull1_mock.calls.last.request.content) == {
        "head": "current-branch/title-commit-1--29617d37",
        "base": "main",
        "title": "Title commit 1",
        "body": "Message commit 1",
        "draft": False,
    }

    # Second pull request is created
    assert len(post_pull2_mock.calls) == 1
    assert json.loads(post_pull2_mock.calls.last.request.content) == {
        "head": "current-branch/title-commit-2--29617d37",
        "base": "current-branch/title-commit-1--29617d37",
        "title": "Title commit 2",
        "body": "Message commit 2\n\nDepends-On: #1",
        "draft": False,
    }

    # First stack comment is created
    assert len(post_comment1_mock.calls) == 1
    expected_body = """This pull request is part of a [Mergify stack](https://docs.mergify.com/stacks/):

| # | Pull Request | Link | |
|--:|---|---|---|
| 1 | Title commit 1 | [#1](https://github.com/repo/user/pull/1) | 👈 |
| 2 | Title commit 2 | [#2](https://github.com/repo/user/pull/2) |  |
"""
    assert json.loads(post_comment1_mock.calls.last.request.content) == {
        "body": expected_body,
    }

    # Second stack comment is created
    assert len(post_comment2_mock.calls) == 1
    expected_body = """This pull request is part of a [Mergify stack](https://docs.mergify.com/stacks/):

| # | Pull Request | Link | |
|--:|---|---|---|
| 1 | Title commit 1 | [#1](https://github.com/repo/user/pull/1) |  |
| 2 | Title commit 2 | [#2](https://github.com/repo/user/pull/2) | 👈 |
"""
    assert json.loads(post_comment2_mock.calls.last.request.content) == {
        "body": expected_body,
    }


@pytest.mark.respx(base_url="https://api.github.com/")
async def test_stack_create_single_pull(
    git_mock: test_utils.GitMock,
    respx_mock: respx.MockRouter,
) -> None:
    # Mock 1 commits on branch `current-branch`
    git_mock.commit(
        test_utils.Commit(
            sha="commit1_sha",
            title="Title commit 1",
            message="Message commit 1",
            change_id="I29617d37762fd69809c255d7e7073cb11f8fbf50",
        ),
    )
    git_mock.finalize()

    # Mock HTTP calls
    respx_mock.get("/user").respond(200, json={"login": "author"})
    respx_mock.get("/search/issues").respond(200, json={"items": []})

    post_pull_mock = respx_mock.post(
        "/repos/user/repo/pulls",
        json__title="Title commit 1",
    ).respond(
        200,
        json={
            "html_url": "https://github.com/repo/user/pull/1",
            "number": "1",
            "title": "Title commit 1",
            "head": {"sha": "commit1_sha"},
            "state": "open",
            "merged_at": None,
            "draft": False,
            "node_id": "",
        },
    )
    respx_mock.get("/repos/user/repo/issues/1/comments").respond(200, json=[])

    await push.stack_push(
        github_server="https://api.github.com/",
        token="",
        skip_rebase=False,
        next_only=False,
        branch_prefix="",
        dry_run=False,
        trunk=("origin", "main"),
    )

    # Pull request is created without stack comment
    assert len(post_pull_mock.calls) == 1
    assert json.loads(post_pull_mock.calls.last.request.content) == {
        "head": "current-branch/title-commit-1--29617d37",
        "base": "main",
        "title": "Title commit 1",
        "body": "Message commit 1",
        "draft": False,
    }


@pytest.mark.respx(base_url="https://api.github.com/")
async def test_stack_update_no_rebase(
    git_mock: test_utils.GitMock,
    respx_mock: respx.MockRouter,
) -> None:
    # Mock 1 commits on branch `current-branch`
    git_mock.commit(
        test_utils.Commit(
            sha="commit_sha",
            title="Title",
            message="Message",
            change_id="I29617d37762fd69809c255d7e7073cb11f8fbf50",
            head_ref="current-branch/I29617d37762fd69809c255d7e7073cb11f8fbf50",
        ),
    )
    git_mock.finalize(
        remote_shas={
            "I29617d37762fd69809c255d7e7073cb11f8fbf50": "previous_commit_sha",
        },
    )

    # Mock HTTP calls: the stack already exists but it's out of date, it should
    # be updated
    respx_mock.get("/user").respond(200, json={"login": "author"})
    respx_mock.get("/search/issues").respond(
        200,
        json={
            "items": [
                {
                    "pull_request": {
                        "url": "https://api.github.com/repos/user/repo/pulls/123",
                    },
                },
            ],
        },
    )

    respx_mock.get(
        "/repos/user/repo/pulls/123",
    ).respond(
        200,
        json={
            "html_url": "",
            "number": "123",
            "title": "Title",
            "head": {
                "sha": "previous_commit_sha",
                "ref": "current-branch/I29617d37762fd69809c255d7e7073cb11f8fbf50",
            },
            "body": "body",
            "state": "open",
            "merged_at": None,
            "draft": False,
            "node_id": "",
        },
    )
    patch_pull_mock = respx_mock.patch("/repos/user/repo/pulls/123").respond(
        200,
        json={},
    )
    respx_mock.get("/repos/user/repo/issues/123/comments").respond(
        200,
        json=[
            {
                "body": "This pull request is part of a stack:\n...",
                "url": "https://api.github.com/repos/user/repo/issues/comments/456",
            },
        ],
    )
    patch_comment_mock = respx_mock.patch(
        "/repos/user/repo/issues/comments/456",
    ).respond(200)
    respx_mock.post("/repos/user/repo/issues/123/comments").respond(200)
    git_mock.mock("fetch", "origin", "refs/pull/123/head", output="")

    with mock.patch.object(push, "detect_change_type", return_value="content"):
        await push.stack_push(
            github_server="https://api.github.com/",
            token="",
            skip_rebase=True,
            next_only=False,
            branch_prefix="",
            dry_run=False,
            trunk=("origin", "main"),
        )
    assert not git_mock.has_been_called_with("pull", "--rebase", "origin", "main")

    # The pull request is updated
    assert len(patch_pull_mock.calls) == 1
    assert json.loads(patch_pull_mock.calls.last.request.content) == {
        "head": "current-branch/I29617d37762fd69809c255d7e7073cb11f8fbf50",
        "base": "main",
        "title": "Title",
        "body": "Message",
    }

    # Old-format stack comment is updated to new table format
    assert len(patch_comment_mock.calls) == 1
    comment_body = json.loads(patch_comment_mock.calls.last.request.content)["body"]
    assert comment_body.startswith(
        "This pull request is part of a [Mergify stack]",
    )


@pytest.mark.respx(base_url="https://api.github.com/")
async def test_stack_update(
    git_mock: test_utils.GitMock,
    respx_mock: respx.MockRouter,
) -> None:
    # Mock 1 commits on branch `current-branch`
    git_mock.commit(
        test_utils.Commit(
            sha="commit_sha",
            title="Title",
            message="Message",
            change_id="I29617d37762fd69809c255d7e7073cb11f8fbf50",
            head_ref="current-branch/I29617d37762fd69809c255d7e7073cb11f8fbf50",
        ),
    )
    git_mock.finalize(
        remote_shas={
            "I29617d37762fd69809c255d7e7073cb11f8fbf50": "previous_commit_sha",
        },
    )

    # Mock HTTP calls: the stack already exists but it's out of date, it should
    # be updated
    respx_mock.get("/user").respond(200, json={"login": "author"})
    respx_mock.get("/search/issues").respond(
        200,
        json={
            "items": [
                {
                    "pull_request": {
                        "url": "https://api.github.com/repos/user/repo/pulls/123",
                    },
                },
            ],
        },
    )

    respx_mock.get(
        "/repos/user/repo/pulls/123",
    ).respond(
        200,
        json={
            "html_url": "",
            "number": "123",
            "title": "Title",
            "head": {
                "sha": "previous_commit_sha",
                "ref": "current-branch/I29617d37762fd69809c255d7e7073cb11f8fbf50",
            },
            "body": "body",
            "state": "open",
            "merged_at": None,
            "draft": False,
            "node_id": "",
        },
    )
    patch_pull_mock = respx_mock.patch("/repos/user/repo/pulls/123").respond(
        200,
        json={},
    )
    respx_mock.get("/repos/user/repo/issues/123/comments").respond(
        200,
        json=[
            {
                "body": "This pull request is part of a stack:\n...",
                "url": "https://api.github.com/repos/user/repo/issues/comments/456",
            },
        ],
    )
    respx_mock.patch("/repos/user/repo/issues/comments/456").respond(200)
    respx_mock.post("/repos/user/repo/issues/123/comments").respond(200)
    git_mock.mock("fetch", "origin", "refs/pull/123/head", output="")

    with mock.patch.object(push, "detect_change_type", return_value="content"):
        await push.stack_push(
            github_server="https://api.github.com/",
            token="",
            skip_rebase=False,
            next_only=False,
            branch_prefix="",
            dry_run=False,
            trunk=("origin", "main"),
        )
    assert git_mock.has_been_called_with("pull", "--rebase", "origin", "main")

    # The pull request is updated
    assert len(patch_pull_mock.calls) == 1
    assert json.loads(patch_pull_mock.calls.last.request.content) == {
        "head": "current-branch/I29617d37762fd69809c255d7e7073cb11f8fbf50",
        "base": "main",
        "title": "Title",
        "body": "Message",
    }


@pytest.mark.respx(base_url="https://api.github.com/")
async def test_stack_update_keep_title_and_body(
    git_mock: test_utils.GitMock,
    respx_mock: respx.MockRouter,
) -> None:
    # Mock 1 commits on branch `current-branch`
    git_mock.commit(
        test_utils.Commit(
            sha="commit_sha",
            title="New Title that should be ignored",
            message="New Message that should be ignored",
            change_id="I29617d37762fd69809c255d7e7073cb11f8fbf50",
            head_ref="current-branch/I29617d37762fd69809c255d7e7073cb11f8fbf50",
        ),
    )
    git_mock.finalize(
        remote_shas={
            "I29617d37762fd69809c255d7e7073cb11f8fbf50": "previous_commit_sha",
        },
    )

    # Mock HTTP calls: the stack already exists but it's out of date, it should
    # be updated
    respx_mock.get("/user").respond(200, json={"login": "author"})
    respx_mock.get("/search/issues").respond(
        200,
        json={
            "items": [
                {
                    "pull_request": {
                        "url": "https://api.github.com/repos/user/repo/pulls/123",
                    },
                },
            ],
        },
    )
    respx_mock.get(
        "/repos/user/repo/pulls/123",
    ).respond(
        200,
        json={
            "html_url": "",
            "number": "123",
            "title": "Title",
            "head": {
                "sha": "previous_commit_sha",
                "ref": "current-branch/I29617d37762fd69809c255d7e7073cb11f8fbf50",
            },
            "state": "open",
            "merged_at": None,
            "draft": False,
            "node_id": "",
            "body": "DONT TOUCH ME\n\nDepends-On: #12345\n",
        },
    )
    patch_pull_mock = respx_mock.patch("/repos/user/repo/pulls/123").respond(
        200,
        json={},
    )
    respx_mock.get("/repos/user/repo/issues/123/comments").respond(
        200,
        json=[
            {
                "body": "This pull request is part of a stack:\n...",
                "url": "https://api.github.com/repos/user/repo/issues/comments/456",
            },
        ],
    )
    respx_mock.patch("/repos/user/repo/issues/comments/456").respond(200)
    respx_mock.post("/repos/user/repo/issues/123/comments").respond(200)
    git_mock.mock("fetch", "origin", "refs/pull/123/head", output="")

    with mock.patch.object(push, "detect_change_type", return_value="content"):
        await push.stack_push(
            github_server="https://api.github.com/",
            token="",
            skip_rebase=False,
            next_only=False,
            branch_prefix="",
            dry_run=False,
            trunk=("origin", "main"),
            keep_pull_request_title_and_body=True,
        )

    # The pull request is updated
    assert len(patch_pull_mock.calls) == 1
    assert json.loads(patch_pull_mock.calls.last.request.content) == {
        "head": "current-branch/I29617d37762fd69809c255d7e7073cb11f8fbf50",
        "base": "main",
        "body": "DONT TOUCH ME",
    }


@pytest.mark.respx(base_url="https://api.github.com/")
async def test_stack_dry_run_does_not_rebase(
    git_mock: test_utils.GitMock,
    respx_mock: respx.MockRouter,
) -> None:
    git_mock.commit(
        test_utils.Commit(
            sha="commit1_sha",
            title="Title commit 1",
            message="Message commit 1",
            change_id="I29617d37762fd69809c255d7e7073cb11f8fbf50",
        ),
    )
    git_mock.finalize()
    git_mock.mock("rev-list", "--count", "HEAD..origin/main", output="0")

    respx_mock.get("/user").respond(200, json={"login": "author"})
    respx_mock.get("/search/issues").respond(200, json={"items": []})

    with pytest.raises(SystemExit, match="0"):
        await push.stack_push(
            github_server="https://api.github.com/",
            token="",
            skip_rebase=False,
            next_only=False,
            branch_prefix="",
            dry_run=True,
            trunk=("origin", "main"),
        )

    # Dry-run never rebases.
    assert not git_mock.has_been_called_with("pull", "--rebase", "origin", "main")

    # No branches are pushed.
    assert not git_mock.has_been_called_with(
        "push",
        "--atomic",
        "--force-with-lease=refs/heads/current-branch/I29617d37762fd69809c255d7e7073cb11f8fbf50:",
        "origin",
        "commit1_sha:refs/heads/current-branch/title-commit-1--29617d37",
    )


@pytest.mark.respx(base_url="https://api.github.com/")
async def test_stack_dry_run_behind_flips_up_to_date_to_update(
    git_mock: test_utils.GitMock,
    respx_mock: respx.MockRouter,
) -> None:
    # PR exists with matching SHA — normally "skip-up-to-date".
    # But branch is behind base, so rebase would change SHAs → "update".
    git_mock.commit(
        test_utils.Commit(
            sha="commit1_sha",
            title="Title commit 1",
            message="Message commit 1",
            change_id="I29617d37762fd69809c255d7e7073cb11f8fbf50",
        ),
    )
    git_mock.finalize()
    git_mock.mock("rev-list", "--count", "HEAD..origin/main", output="3")

    respx_mock.get("/user").respond(200, json={"login": "author"})
    respx_mock.get("/search/issues").respond(
        200,
        json={
            "items": [
                {
                    "pull_request": {
                        "url": "https://api.github.com/repos/user/repo/pulls/42",
                    },
                },
            ],
        },
    )
    respx_mock.get("/repos/user/repo/pulls/42").respond(
        200,
        json={
            "html_url": "",
            "head": {
                "sha": "commit1_sha",
                "ref": "current-branch/I29617d37762fd69809c255d7e7073cb11f8fbf50",
            },
            "state": "open",
            "merged_at": None,
            "draft": False,
        },
    )

    with pytest.raises(SystemExit, match="0"):
        await push.stack_push(
            github_server="https://api.github.com/",
            token="",
            skip_rebase=False,
            next_only=False,
            branch_prefix="",
            dry_run=True,
            trunk=("origin", "main"),
        )

    # Dry-run never rebases.
    assert not git_mock.has_been_called_with("pull", "--rebase", "origin", "main")


@pytest.mark.respx(base_url="https://api.github.com/")
async def test_stack_dry_run_skip_rebase(
    git_mock: test_utils.GitMock,
    respx_mock: respx.MockRouter,
) -> None:
    git_mock.commit(
        test_utils.Commit(
            sha="commit1_sha",
            title="Title commit 1",
            message="Message commit 1",
            change_id="I29617d37762fd69809c255d7e7073cb11f8fbf50",
        ),
    )
    git_mock.finalize()

    respx_mock.get("/user").respond(200, json={"login": "author"})
    respx_mock.get("/search/issues").respond(200, json={"items": []})

    with pytest.raises(SystemExit, match="0"):
        await push.stack_push(
            github_server="https://api.github.com/",
            token="",
            skip_rebase=True,
            next_only=False,
            branch_prefix="",
            dry_run=True,
            trunk=("origin", "main"),
        )

    # Rebase check is skipped when --skip-rebase is passed.
    assert not git_mock.has_been_called_with("rev-list", "--count", "HEAD..origin/main")
    assert not git_mock.has_been_called_with("pull", "--rebase", "origin", "main")


@pytest.mark.respx(base_url="https://api.github.com/")
async def test_stack_on_destination_branch_raises_an_error(
    git_mock: test_utils.GitMock,
    respx_mock: respx.MockRouter,
) -> None:
    respx_mock.get("/user").respond(200, json={"login": "author"})
    git_mock.mock("rev-parse", "--abbrev-ref", "HEAD", output="main")
    git_mock.mock(
        "remote",
        "get-url",
        "origin",
        output="https://github.com/foo/bar.git",
    )

    with pytest.raises(SystemExit, match=str(ExitCode.INVALID_STATE)):
        await push.stack_push(
            github_server="https://api.github.com/",
            token="",
            skip_rebase=False,
            next_only=False,
            branch_prefix="",
            dry_run=False,
            trunk=("origin", "main"),
        )


@pytest.mark.respx(base_url="https://api.github.com/")
async def test_stack_without_common_commit_raises_an_error(
    git_mock: test_utils.GitMock,
    respx_mock: respx.MockRouter,
) -> None:
    respx_mock.get("/user").respond(200, json={"login": "author"})
    git_mock.mock("merge-base", "--fork-point", "origin/main", output="")

    with pytest.raises(SystemExit, match=str(ExitCode.STACK_NOT_FOUND)):
        await push.stack_push(
            github_server="https://api.github.com/",
            token="",
            skip_rebase=False,
            next_only=False,
            branch_prefix="",
            dry_run=False,
            trunk=("origin", "main"),
        )


def test_replace_local_action_flips_up_to_date() -> None:
    def _make_local_change(action: changes.ActionT) -> changes.LocalChange:
        return changes.LocalChange(
            id=changes.ChangeId(""),
            pull=None,
            commit_sha="",
            title="",
            message="",
            base_branch="",
            dest_branch="",
            action=action,
        )

    planned = changes.Changes(stack_prefix="")
    planned.locals.append(_make_local_change("skip-up-to-date"))
    planned.locals.append(_make_local_change("create"))

    planned.replace_local_action(old="skip-up-to-date", new="update")

    assert planned.locals[0].action == "update"
    assert planned.locals[1].action == "create"


@pytest.mark.respx(base_url="https://api.github.com/")
async def test_get_remote_changes_search_query_uses_trailing_slash(
    respx_mock: respx.MockRouter,
) -> None:
    """Ensure the search query uses `head:<prefix>/` (trailing slash) to avoid
    matching branches from similarly-named stacks (e.g. `my-stack` matching
    `my-stack-2/...`)."""
    import httpx

    search_mock = respx_mock.get("/search/issues").respond(
        200,
        json={"items": []},
    )

    async with httpx.AsyncClient(base_url="https://api.github.com/") as client:
        await changes.get_remote_changes(
            client,
            user="user",
            repo="repo",
            stack_prefix="my-stack",
            author="author",
        )

    assert len(search_mock.calls) == 1
    query = search_mock.calls.last.request.url.params["q"]
    assert "head:my-stack/" in query, (
        f"Expected 'head:my-stack/' (with trailing slash) in query, got: {query}"
    )


@pytest.mark.parametrize(
    ("config_value", "expected"),
    [
        ("true", True),
        ("false", False),
        ("", True),  # default when empty
    ],
)
async def test_get_default_revision_history(
    git_mock: test_utils.GitMock,
    *,
    config_value: str,
    expected: bool,
) -> None:
    git_mock.mock(
        "config",
        "--get",
        "mergify-cli.stack-revision-history",
        output=config_value,
    )
    result = await utils.get_default_revision_history()
    assert result == expected


async def test_get_default_revision_history_not_set() -> None:
    # When config key doesn't exist, git raises an error — default to True
    with mock.patch.object(
        utils,
        "git",
        side_effect=utils.CommandError(
            ("config", "--get", "mergify-cli.stack-revision-history"),
            1,
            b"",
        ),
    ):
        result = await utils.get_default_revision_history()
    assert result is True


async def test_detect_change_type_content() -> None:
    with mock.patch.object(push, "_git_patch_id", side_effect=["aaa", "bbb"]):
        result = await push.detect_change_type("old_sha", "new_sha")
    assert result == "content"


async def test_detect_change_type_rebase() -> None:
    with mock.patch.object(push, "_git_patch_id", side_effect=["aaa", "aaa"]):
        result = await push.detect_change_type("old_sha", "new_sha")
    assert result == "rebase"


async def test_detect_change_type_error_falls_back_to_unknown() -> None:
    with mock.patch.object(
        push,
        "_git_patch_id",
        side_effect=utils.CommandError(("git",), 1, b""),
    ):
        result = await push.detect_change_type("old_sha", "new_sha")
    assert result == "unknown"


async def test_fetch_old_pr_heads(
    git_mock: test_utils.GitMock,
) -> None:
    git_mock.mock(
        "fetch",
        "origin",
        "refs/pull/1/head",
        "refs/pull/2/head",
        output="",
    )
    await push.fetch_old_pr_heads("origin", [1, 2])


async def test_fetch_old_pr_heads_empty() -> None:
    # No PRs to fetch — should not call git fetch at all
    await push.fetch_old_pr_heads("origin", [])


def test_revision_history_comment_first_update() -> None:
    """First update creates a comment with initial + update rows."""
    comment = push.RevisionHistoryComment.create_initial(
        github_server="https://api.github.com",
        user="owner",
        repo="repo",
        old_sha="abc1234567890abcdef1234567890abcdef123456",
        new_sha="def5678901234567890abcdef1234567890abcdef",
        change_type="content",
        timestamp=datetime.datetime(2026, 4, 14, 14, 30, tzinfo=datetime.UTC),
    )
    body = comment.body(pull_number=1)
    assert body.startswith("### Revision history\n")
    assert "| 1 | initial |" in body
    assert "`abc1234`" in body
    assert "| 2 | content |" in body
    assert (
        "abc1234567890abcdef1234567890abcdef123456...def5678901234567890abcdef1234567890abcdef"
        in body
    )
    assert "2026-04-14 14:30 UTC" in body


def test_revision_history_comment_append() -> None:
    """Appending adds a new row to existing comment."""
    comment = push.RevisionHistoryComment.create_initial(
        github_server="https://api.github.com",
        user="owner",
        repo="repo",
        old_sha="abc1234567890abcdef1234567890abcdef123456",
        new_sha="def5678901234567890abcdef1234567890abcdef",
        change_type="content",
        timestamp=datetime.datetime(2026, 4, 14, 14, 30, tzinfo=datetime.UTC),
    )
    comment.append(
        old_sha="def5678901234567890abcdef1234567890abcdef",
        new_sha="789abcdef01234567890abcdef01234567890abcd",
        change_type="rebase",
        timestamp=datetime.datetime(2026, 4, 15, 9, 10, tzinfo=datetime.UTC),
    )
    body = comment.body(pull_number=1)
    assert "| 3 | rebase |" in body
    assert (
        "def5678901234567890abcdef1234567890abcdef...789abcdef01234567890abcdef01234567890abcd"
        in body
    )
    assert "2026-04-15 09:10 UTC" in body


def test_revision_history_comment_parse_existing() -> None:
    """Parse an existing comment body back into a RevisionHistoryComment."""
    original = push.RevisionHistoryComment.create_initial(
        github_server="https://api.github.com",
        user="owner",
        repo="repo",
        old_sha="abc1234567890abcdef1234567890abcdef123456",
        new_sha="def5678901234567890abcdef1234567890abcdef",
        change_type="content",
        timestamp=datetime.datetime(2026, 4, 14, 14, 30, tzinfo=datetime.UTC),
    )
    body = original.body(pull_number=1)

    parsed = push.RevisionHistoryComment.parse(
        body,
        github_server="https://api.github.com",
        user="owner",
        repo="repo",
    )
    assert parsed is not None
    # Append to the parsed comment
    parsed.append(
        old_sha="def5678901234567890abcdef1234567890abcdef",
        new_sha="789abcdef01234567890abcdef01234567890abcd",
        change_type="rebase",
        timestamp=datetime.datetime(2026, 4, 15, 9, 10, tzinfo=datetime.UTC),
    )
    new_body = parsed.body(pull_number=1)
    assert "| 3 | rebase |" in new_body
    # Verify old rows are preserved verbatim (compare links intact)
    assert (
        "abc1234567890abcdef1234567890abcdef123456...def5678901234567890abcdef1234567890abcdef"
        in new_body
    )
    assert "| 1 | initial |" in new_body
    assert "| 2 | content |" in new_body


def test_revision_history_comment_parse_returns_none_for_non_matching() -> None:
    parsed = push.RevisionHistoryComment.parse(
        "Some other comment",
        github_server="https://api.github.com",
        user="owner",
        repo="repo",
    )
    assert parsed is None


def test_revision_history_is_revision_comment() -> None:
    assert push.RevisionHistoryComment.is_revision_comment(
        {"body": "### Revision history\n...", "url": ""},
    )
    assert not push.RevisionHistoryComment.is_revision_comment(
        {"body": "Some other comment", "url": ""},
    )


def test_revision_history_initial_populates_timestamp_iso() -> None:
    comment = push.RevisionHistoryComment.create_initial(
        github_server="https://api.github.com",
        user="owner",
        repo="repo",
        old_sha="abc1234567890abcdef1234567890abcdef123456",
        new_sha="def5678901234567890abcdef1234567890abcdef",
        change_type="content",
        timestamp=datetime.datetime(2026, 4, 14, 14, 30, tzinfo=datetime.UTC),
    )
    assert comment.entries[0].timestamp_iso == "2026-04-14T14:30:00Z"
    assert comment.entries[1].timestamp_iso == "2026-04-14T14:30:00Z"


def test_revision_history_append_populates_timestamp_iso() -> None:
    comment = push.RevisionHistoryComment.create_initial(
        github_server="https://api.github.com",
        user="owner",
        repo="repo",
        old_sha="abc1234567890abcdef1234567890abcdef123456",
        new_sha="def5678901234567890abcdef1234567890abcdef",
        change_type="content",
        timestamp=datetime.datetime(2026, 4, 14, 14, 30, tzinfo=datetime.UTC),
    )
    comment.append(
        old_sha="def5678901234567890abcdef1234567890abcdef",
        new_sha="789abcdef01234567890abcdef01234567890abcd",
        change_type="rebase",
        timestamp=datetime.datetime(2026, 4, 15, 9, 10, 45, tzinfo=datetime.UTC),
    )
    assert comment.entries[2].timestamp_iso == "2026-04-15T09:10:45Z"


def test_revision_history_comment_unknown_type() -> None:
    comment = push.RevisionHistoryComment.create_initial(
        github_server="https://api.github.com",
        user="owner",
        repo="repo",
        old_sha="abc1234567890abcdef1234567890abcdef123456",
        new_sha="def5678901234567890abcdef1234567890abcdef",
        change_type="unknown",
        timestamp=datetime.datetime(2026, 4, 14, 14, 30, tzinfo=datetime.UTC),
    )
    body = comment.body(pull_number=1)
    assert "| 2 | unknown |" in body


def test_revision_history_body_contains_json_marker() -> None:
    comment = push.RevisionHistoryComment.create_initial(
        github_server="https://api.github.com",
        user="owner",
        repo="repo",
        old_sha="abc1234567890abcdef1234567890abcdef123456",
        new_sha="def5678901234567890abcdef1234567890abcdef",
        change_type="content",
        timestamp=datetime.datetime(2026, 4, 14, 14, 30, tzinfo=datetime.UTC),
    )
    body = comment.body(pull_number=42)

    marker_prefix = "<!-- mergify-revision-data: "
    marker_lines = [
        line for line in body.splitlines() if line.startswith(marker_prefix)
    ]
    assert len(marker_lines) == 1
    assert marker_lines[0].endswith(" -->")

    payload_str = marker_lines[0][len(marker_prefix) : -len(" -->")]
    payload = json.loads(payload_str)

    assert payload == {
        "schema_version": 1,
        "pull_number": 42,
        "entries": [
            {
                "number": 1,
                "change_type": "initial",
                "old_sha": None,
                "new_sha": "abc1234567890abcdef1234567890abcdef123456",
                "timestamp_iso": "2026-04-14T14:30:00Z",
                "compare_url": None,
            },
            {
                "number": 2,
                "change_type": "content",
                "old_sha": "abc1234567890abcdef1234567890abcdef123456",
                "new_sha": "def5678901234567890abcdef1234567890abcdef",
                "timestamp_iso": "2026-04-14T14:30:00Z",
                "compare_url": (
                    "https://github.com/owner/repo/compare/"
                    "abc1234567890abcdef1234567890abcdef123456..."
                    "def5678901234567890abcdef1234567890abcdef"
                ),
            },
        ],
    }


def test_revision_history_body_json_marker_is_single_line_compact() -> None:
    comment = push.RevisionHistoryComment.create_initial(
        github_server="https://api.github.com",
        user="owner",
        repo="repo",
        old_sha="abc1234567890abcdef1234567890abcdef123456",
        new_sha="def5678901234567890abcdef1234567890abcdef",
        change_type="rebase",
        timestamp=datetime.datetime(2026, 4, 14, 14, 30, tzinfo=datetime.UTC),
    )
    body = comment.body(pull_number=7)
    marker_prefix = "<!-- mergify-revision-data: "
    marker_line = next(
        line for line in body.splitlines() if line.startswith(marker_prefix)
    )
    # Compact form: no spaces after separators.
    assert '", ' not in marker_line
    assert '": ' not in marker_line


@pytest.mark.respx(base_url="https://api.github.com/")
async def test_create_revision_comment_on_update(
    git_mock: test_utils.GitMock,
    respx_mock: respx.MockRouter,
) -> None:
    """When a PR is updated (force-pushed), a revision history comment is created."""
    git_mock.commit(
        test_utils.Commit(
            sha="new_commit_sha",
            title="Title",
            message="Message",
            change_id="I29617d37762fd69809c255d7e7073cb11f8fbf50",
            head_ref="current-branch/I29617d37762fd69809c255d7e7073cb11f8fbf50",
        ),
    )
    git_mock.finalize(
        remote_shas={"I29617d37762fd69809c255d7e7073cb11f8fbf50": "old_commit_sha"},
    )
    git_mock.mock(
        "fetch",
        "origin",
        "refs/pull/123/head",
        output="",
    )

    respx_mock.get("/user").respond(200, json={"login": "author"})
    respx_mock.get("/search/issues").respond(
        200,
        json={
            "items": [
                {
                    "pull_request": {
                        "url": "https://api.github.com/repos/user/repo/pulls/123",
                    },
                },
            ],
        },
    )
    respx_mock.get("/repos/user/repo/pulls/123").respond(
        200,
        json={
            "html_url": "https://github.com/user/repo/pull/123",
            "number": "123",
            "title": "Title",
            "head": {
                "sha": "old_commit_sha",
                "ref": "current-branch/I29617d37762fd69809c255d7e7073cb11f8fbf50",
            },
            "body": "body",
            "state": "open",
            "merged_at": None,
            "draft": False,
            "node_id": "",
        },
    )
    respx_mock.patch("/repos/user/repo/pulls/123").respond(200, json={})
    # Stack comment (existing)
    respx_mock.get("/repos/user/repo/issues/123/comments").respond(
        200,
        json=[
            {
                "body": "This pull request is part of a stack:\n...",
                "url": "https://api.github.com/repos/user/repo/issues/comments/456",
            },
        ],
    )
    respx_mock.patch("/repos/user/repo/issues/comments/456").respond(200)
    # Revision comment will be POSTed (no existing one in the comments list)
    post_revision_mock = respx_mock.post(
        "/repos/user/repo/issues/123/comments",
    ).respond(200)

    with mock.patch.object(push, "detect_change_type", return_value="content"):
        await push.stack_push(
            github_server="https://api.github.com/",
            token="",
            skip_rebase=False,
            next_only=False,
            branch_prefix="",
            dry_run=False,
            trunk=("origin", "main"),
        )

    # A revision history comment should have been posted
    assert post_revision_mock.called
    # The last POST to comments should be the revision history
    revision_calls = [
        call
        for call in post_revision_mock.calls
        if json.loads(call.request.content)
        .get("body", "")
        .startswith("### Revision history")
    ]
    assert len(revision_calls) == 1
    posted_body = json.loads(revision_calls[0].request.content)["body"]
    assert "content" in posted_body
    assert "old_com" in posted_body  # old_commit_sha[:7]
    assert "new_com" in posted_body  # new_commit_sha[:7]


@pytest.mark.respx(base_url="https://api.github.com/")
async def test_no_revision_comment_on_create(
    git_mock: test_utils.GitMock,
    respx_mock: respx.MockRouter,
) -> None:
    """When a PR is created (not updated), no revision history comment is posted."""
    git_mock.commit(
        test_utils.Commit(
            sha="commit1_sha",
            title="Title commit 1",
            message="Message commit 1",
            change_id="I29617d37762fd69809c255d7e7073cb11f8fbf50",
        ),
    )
    git_mock.finalize()

    respx_mock.get("/user").respond(200, json={"login": "author"})
    respx_mock.get("/search/issues").respond(200, json={"items": []})
    respx_mock.post("/repos/user/repo/pulls").respond(
        200,
        json={
            "html_url": "https://github.com/user/repo/pull/1",
            "number": "1",
            "title": "Title commit 1",
            "head": {"sha": "commit1_sha"},
            "state": "open",
            "merged_at": None,
            "draft": False,
            "node_id": "",
        },
    )
    respx_mock.get("/repos/user/repo/issues/1/comments").respond(200, json=[])

    await push.stack_push(
        github_server="https://api.github.com/",
        token="",
        skip_rebase=False,
        next_only=False,
        branch_prefix="",
        dry_run=False,
        trunk=("origin", "main"),
    )

    # Verify no revision history comment was posted
    for call in respx_mock.calls:
        if call.request.method == "POST" and "/comments" in str(call.request.url):
            posted = json.loads(call.request.content)
            assert not posted.get("body", "").startswith("### Revision history")


@pytest.mark.respx(base_url="https://api.github.com/")
async def test_no_revision_history_flag_skips_revision_comments(
    git_mock: test_utils.GitMock,
    respx_mock: respx.MockRouter,
) -> None:
    git_mock.commit(
        test_utils.Commit(
            sha="new_commit_sha",
            title="Title",
            message="Message",
            change_id="I29617d37762fd69809c255d7e7073cb11f8fbf50",
            head_ref="current-branch/I29617d37762fd69809c255d7e7073cb11f8fbf50",
        ),
    )
    git_mock.finalize(
        remote_shas={"I29617d37762fd69809c255d7e7073cb11f8fbf50": "old_commit_sha"},
    )

    respx_mock.get("/user").respond(200, json={"login": "author"})
    respx_mock.get("/search/issues").respond(
        200,
        json={
            "items": [
                {
                    "pull_request": {
                        "url": "https://api.github.com/repos/user/repo/pulls/123",
                    },
                },
            ],
        },
    )
    respx_mock.get("/repos/user/repo/pulls/123").respond(
        200,
        json={
            "html_url": "",
            "number": "123",
            "title": "Title",
            "head": {
                "sha": "old_commit_sha",
                "ref": "current-branch/I29617d37762fd69809c255d7e7073cb11f8fbf50",
            },
            "body": "body",
            "state": "open",
            "merged_at": None,
            "draft": False,
            "node_id": "",
        },
    )
    respx_mock.patch("/repos/user/repo/pulls/123").respond(200, json={})
    respx_mock.get("/repos/user/repo/issues/123/comments").respond(
        200,
        json=[
            {
                "body": "This pull request is part of a stack:\n...",
                "url": "https://api.github.com/repos/user/repo/issues/comments/456",
            },
        ],
    )
    respx_mock.patch("/repos/user/repo/issues/comments/456").respond(200)

    await push.stack_push(
        github_server="https://api.github.com/",
        token="",
        skip_rebase=False,
        next_only=False,
        branch_prefix="",
        dry_run=False,
        trunk=("origin", "main"),
        revision_history=False,
    )

    # No fetch of PR heads
    assert not git_mock.has_been_called_with("fetch", "origin", "refs/pull/123/head")
    # No revision comment posted
    for call in respx_mock.calls:
        if call.request.method == "POST" and "/comments" in str(call.request.url):
            posted = json.loads(call.request.content)
            assert not posted.get("body", "").startswith("### Revision history")


@pytest.mark.respx(base_url="https://api.github.com/")
async def test_revision_comment_updated_on_second_push(
    git_mock: test_utils.GitMock,
    respx_mock: respx.MockRouter,
) -> None:
    """On a second force-push, the existing revision comment is updated, not duplicated."""
    git_mock.commit(
        test_utils.Commit(
            sha="third_sha",
            title="Title",
            message="Message",
            change_id="I29617d37762fd69809c255d7e7073cb11f8fbf50",
            head_ref="current-branch/I29617d37762fd69809c255d7e7073cb11f8fbf50",
        ),
    )
    git_mock.finalize(
        remote_shas={"I29617d37762fd69809c255d7e7073cb11f8fbf50": "second_sha"},
    )
    git_mock.mock("fetch", "origin", "refs/pull/123/head", output="")

    respx_mock.get("/user").respond(200, json={"login": "author"})
    respx_mock.get("/search/issues").respond(
        200,
        json={
            "items": [
                {
                    "pull_request": {
                        "url": "https://api.github.com/repos/user/repo/pulls/123",
                    },
                },
            ],
        },
    )
    respx_mock.get("/repos/user/repo/pulls/123").respond(
        200,
        json={
            "html_url": "https://github.com/user/repo/pull/123",
            "number": "123",
            "title": "Title",
            "head": {
                "sha": "second_sha",
                "ref": "current-branch/I29617d37762fd69809c255d7e7073cb11f8fbf50",
            },
            "body": "body",
            "state": "open",
            "merged_at": None,
            "draft": False,
            "node_id": "",
        },
    )
    respx_mock.patch("/repos/user/repo/pulls/123").respond(200, json={})

    # Existing comments: stack comment + existing revision comment
    existing_revision_body = (
        "### Revision history\n"
        "| # | Type | Changes | Date |\n"
        "|---|------|---------|------|\n"
        "| 1 | initial | `first_s` | 2026-04-14 10:00 UTC |\n"
        "| 2 | content | [`first_s \u2192 second_`](https://github.com/user/repo/compare/first_s...second_) | 2026-04-14 12:00 UTC |\n"
    )
    respx_mock.get("/repos/user/repo/issues/123/comments").respond(
        200,
        json=[
            {
                "body": "This pull request is part of a stack:\n...",
                "url": "https://api.github.com/repos/user/repo/issues/comments/456",
            },
            {
                "body": existing_revision_body,
                "url": "https://api.github.com/repos/user/repo/issues/comments/789",
            },
        ],
    )
    respx_mock.patch("/repos/user/repo/issues/comments/456").respond(200)
    patch_revision_mock = respx_mock.patch(
        "/repos/user/repo/issues/comments/789",
    ).respond(200)

    with mock.patch.object(push, "detect_change_type", return_value="rebase"):
        await push.stack_push(
            github_server="https://api.github.com/",
            token="",
            skip_rebase=False,
            next_only=False,
            branch_prefix="",
            dry_run=False,
            trunk=("origin", "main"),
        )

    # The existing revision comment is PATCHED, not a new one POSTed
    assert patch_revision_mock.called
    patched_body = json.loads(patch_revision_mock.calls.last.request.content)["body"]
    assert "| 3 | rebase |" in patched_body
    assert "second_" in patched_body  # old sha
    assert "third_s" in patched_body  # new sha


def test_check_local_branch_invalid_new_format() -> None:
    """Branches ending with --hex8 are also detected as generated branches."""
    with pytest.raises(
        push.LocalBranchInvalidError,
        match="Local branch is a branch generated by Mergify CLI",
    ):
        push.check_local_branch(
            branch_name="prefix/my-branch/add-auth-model--29617d37",
            branch_prefix="prefix",
        )


@pytest.mark.parametrize(
    "valid_branch_name",
    [
        "my-branch",
        "prefix/my-branch",
        "my-branch--not-hex-gg",
        "my-branch--short",
    ],
)
def test_check_local_branch_valid_new_format(valid_branch_name: str) -> None:
    push.check_local_branch(
        branch_name=valid_branch_name,
        branch_prefix="prefix",
    )


def test_is_change_id_valid() -> None:
    assert changes.is_change_id("I29617d37762fd69809c255d7e7073cb11f8fbf50") is True


def test_is_change_id_invalid() -> None:
    assert changes.is_change_id("add-auth-model--29617d37") is False
    assert changes.is_change_id("29617d37") is False
    assert changes.is_change_id("I2961") is False
    assert changes.is_change_id("") is False


def test_extract_short_changeid_new_format() -> None:
    assert changes.extract_changeid_from_branch_segment(
        "add-auth-model--29617d37",
    ) == changes.ChangeId("29617d37")


def test_extract_short_changeid_old_format() -> None:
    assert changes.extract_changeid_from_branch_segment(
        "I29617d37762fd69809c255d7e7073cb11f8fbf50",
    ) == changes.ChangeId("I29617d37762fd69809c255d7e7073cb11f8fbf50")


def test_extract_short_changeid_invalid() -> None:
    assert changes.extract_changeid_from_branch_segment("random-branch") is None


def test_pop_remote_change_exact_match() -> None:
    pull: github_types.PullRequest = {"number": 1}  # type: ignore[typeddict-item]
    remote = changes.RemoteChanges(
        {
            changes.ChangeId("I29617d37762fd69809c255d7e7073cb11f8fbf50"): pull,
        },
    )
    result = changes.pop_remote_change(
        remote,
        changes.ChangeId("I29617d37762fd69809c255d7e7073cb11f8fbf50"),
    )
    assert result is pull
    assert len(remote) == 0


def test_pop_remote_change_short_remote_vs_full_local() -> None:
    pull: github_types.PullRequest = {"number": 1}  # type: ignore[typeddict-item]
    remote = changes.RemoteChanges(
        {
            changes.ChangeId("29617d37"): pull,
        },
    )
    result = changes.pop_remote_change(
        remote,
        changes.ChangeId("I29617d37762fd69809c255d7e7073cb11f8fbf50"),
    )
    assert result is pull
    assert len(remote) == 0


def test_pop_remote_change_no_match() -> None:
    pull: github_types.PullRequest = {"number": 1}  # type: ignore[typeddict-item]
    remote = changes.RemoteChanges(
        {
            changes.ChangeId("Iaaaaaaaa762fd69809c255d7e7073cb11f8fbf50"): pull,
        },
    )
    result = changes.pop_remote_change(
        remote,
        changes.ChangeId("Ibbbbbbbb762fd69809c255d7e7073cb11f8fbf50"),
    )
    assert result is None
    assert len(remote) == 1


@pytest.mark.respx(base_url="https://api.github.com/")
async def test_get_remote_changes_new_format_branch(
    respx_mock: respx.MockRouter,
) -> None:
    """get_remote_changes correctly extracts Change-Id from new-format slug--hex8 branches."""
    import httpx

    respx_mock.get("/search/issues").respond(
        200,
        json={
            "items": [
                {
                    "pull_request": {
                        "url": "https://api.github.com/repos/user/repo/pulls/1",
                    },
                },
            ],
        },
    )
    respx_mock.get("/repos/user/repo/pulls/1").respond(
        200,
        json={
            "html_url": "https://github.com/user/repo/pull/1",
            "number": 1,
            "title": "Add auth model",
            "head": {
                "sha": "abc123",
                "ref": "my-stack/add-auth-model--29617d37",
            },
            "body": "description",
            "state": "open",
            "merged_at": None,
            "draft": False,
            "node_id": "",
        },
    )

    async with httpx.AsyncClient(base_url="https://api.github.com/") as client:
        result = await changes.get_remote_changes(
            client,
            user="user",
            repo="repo",
            stack_prefix="my-stack",
            author="author",
        )

    assert len(result) == 1
    assert changes.ChangeId("29617d37") in result


@pytest.mark.respx(base_url="https://api.github.com/")
async def test_get_remote_changes_old_format_branch(
    respx_mock: respx.MockRouter,
) -> None:
    """get_remote_changes still works with old-format I-prefixed branches."""
    import httpx

    respx_mock.get("/search/issues").respond(
        200,
        json={
            "items": [
                {
                    "pull_request": {
                        "url": "https://api.github.com/repos/user/repo/pulls/1",
                    },
                },
            ],
        },
    )
    respx_mock.get("/repos/user/repo/pulls/1").respond(
        200,
        json={
            "html_url": "https://github.com/user/repo/pull/1",
            "number": 1,
            "title": "Add auth model",
            "head": {
                "sha": "abc123",
                "ref": "my-stack/I29617d37762fd69809c255d7e7073cb11f8fbf50",
            },
            "body": "description",
            "state": "open",
            "merged_at": None,
            "draft": False,
            "node_id": "",
        },
    )

    async with httpx.AsyncClient(base_url="https://api.github.com/") as client:
        result = await changes.get_remote_changes(
            client,
            user="user",
            repo="repo",
            stack_prefix="my-stack",
            author="author",
        )

    assert len(result) == 1
    cid = changes.ChangeId("I29617d37762fd69809c255d7e7073cb11f8fbf50")
    assert cid in result


def test_format_timestamp_iso_normalises_to_utc() -> None:
    tz_ist = datetime.timezone(datetime.timedelta(hours=5, minutes=30))
    dt = datetime.datetime(2026, 4, 14, 20, 0, 0, tzinfo=tz_ist)  # 14:30:00 UTC
    assert (
        push.RevisionHistoryComment._format_timestamp_iso(dt) == "2026-04-14T14:30:00Z"
    )
